import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://lh3.googleusercontent.com/p/AF1QipMznnW4QzhVdG5MPOeIu1Hv9zn2dJMQ9Nj5wpFN=s1360-w1360-h1020",
    title: "Salle LE SAPHIR",
    star: <AiFillStar className="rating-star" />,
    reviews: "(15 reviews)",
    prevPrice: "200DT",
    newPrice: "150",
    typeS: "Open Space",
    state: "Kasserine",
    category: "wedding room",
  },
  {
    img: "https://scontent.ftun10-1.fna.fbcdn.net/v/t39.30808-6/331492089_866961201045286_7629455412958619480_n.jpg?_nc_cat=107&ccb=1-7&_nc_sid=5f2048&_nc_ohc=Iab1_tJuHGAQ7kNvgGJy4-m&_nc_ht=scontent.ftun10-1.fna&oh=00_AfBaauGvJg4SCr_z8_3m_bR9Vhm1xh-S3eDkcEknwXS19Q&oe=662F13A4",
    title: "HAPPY DAY",
    star: <AiFillStar className="rating-star" />,
    reviews: "(103 reviews)",
    prevPrice: "700DT",
    newPrice: "500",
    typeS: "Closed Space",
    state: "Kasserine",
    category: "wedding room",
  },
  {
    img: "https://lh3.googleusercontent.com/p/AF1QipNb5nM5RG-kUsFsr55eHRCjF9xqPw3kqayY19zx=s3072-w3072-h1512-rw",
    title: "Iron Gym",
    star: <AiFillStar className="rating-star" />,
    reviews: "(26 reviews)",
    prevPrice: "1700DT",
    newPrice: "1500",
    typeS: "Closed Space",
    state: "Kasserine",
    category: "gym",
  },
  {
    img: "https://lh5.googleusercontent.com/p/AF1QipMmsfCjEBmaL1eoTF1VWw0dxLgQKBzFp1sein11=w296-h168-n-k-no",
    title: "Academy Gym",
    star: <AiFillStar className="rating-star" />,
    reviews: "(19 reviews)",
    prevPrice: "2300DT",
    newPrice: "2000",
    typeS: "Closed Space",
    state: "Kasserine",
    category: "gym",
  },
  {
    img: "https://lh5.googleusercontent.com/p/AF1QipMdGJiW4uyEJcOmj5LIcQaOMOB2a5i2mMOTH91K=w231-h165-n-k-no-nu",
    title: "WhatSpace",
    star: <AiFillStar className="rating-star" />,
    reviews: "(49 reviews)",
    prevPrice: "",
    newPrice: "500",
    typeS: "Closed Space",
    state: "Tunis",
    category: "meeting room",
  },
  {
    img: "https://lh5.googleusercontent.com/p/AF1QipPfhLS5Kes2Yym6bxIO0ON32d2hUTjZF1TtCA-Z=w296-h168-n-k-no",
    title: "ARENA",
    star: <AiFillStar className="rating-star" />,
    reviews: "(20 reviews)",
    prevPrice: "",
    newPrice: "1500",
    typeS: "Closed Space",
    state: "Tunis",
    category: "event room",
  },
  {
    img: "https://lh5.googleusercontent.com/p/AF1QipPntIzXGjXWOJZ79CgpPVV3JR7T0a7RqbQw_jrT=w296-h168-n-k-no",
    title: "The White House",
    star: <AiFillStar className="rating-star" />,
    reviews: "(20 reviews)",
    prevPrice: "1100DT",
    newPrice: "500",
    typeS: "Closed Space",
    state: "Sousse",
    category: "event room",
  },
];

export default data;
